objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Department__c</fullName>
        <label>IT Department</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>DEV</fullName>
                </value>
                <value>
                    <fullName>PMO</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmployeeSkill__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Time__c</fullName>
        <label>Assigned Time</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>EmployeeSkills</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>EmployeeSkills</relationshipLabel>
        <relationshipName>EmployeeSkills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EmployeeSkill</label>
    <nameField>
        <label>Employe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmployeeSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hot</fullName>
                </value>
                <value>
                    <fullName>Hight</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Owner</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects (Project Owner)</relationshipLabel>
        <relationshipName>Projects_Owner</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Lead__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Team Lead</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects (Team Lead)</relationshipLabel>
        <relationshipName>Projects_Lead</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Middle</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Architector</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

classes/TestTriggerEmployeeSkill.cls
@isTest
private class TestTriggerEmployeeSkill {

    @testSetup static void setup() {
        Employee__c employee1 = new Employee__c(
            First_Name__c = 'TestFirst',
            Last_Name__c = 'TestLast',
            Birthday__c = System.today() - 10,
            IT_Department__c = 'QA',
            Level__c = 'Junior',
            Start_Date__c = System.today()
        );
 
        insert employee1;

        Project__c project1 = new Project__c(
            Name = 'Test1',
            Start_Date__c = System.today() - 10,
            Priority__c = 'Hot',
            Team_Lead__c = employee1.Id,
            Project_Owner__c = employee1.Id
        );

        insert project1;

        EmployeeSkill__c employeeSkill1 = new EmployeeSkill__c(
            Name = 'Test1',
            Assigned_Time__c = 1,
            Employee__c = employee1.Id,
            Project__c = project1.Id
        );
 
        insert employeeSkill1;

        EmployeeSkill__c employeeSkill2 = new EmployeeSkill__c(
            Name = 'Test2',
            Assigned_Time__c = 1,
            Employee__c = employee1.Id,
            Project__c = project1.Id
        );
 
        insert employeeSkill2;
    }

    @isTest static void TestInsert() {

        Employee__c[] employeeList = [
            SELECT Id
            FROM Employee__c
            WHERE First_Name__c = 'TestFirst'
        ];
        
        Employee__c employee1 = employeeList[0];

        Project__c[] projectList = [
            SELECT Id
            FROM Project__c
            WHERE Name = 'Test1'
        ];

        Project__c project1 = projectList[0];

        EmployeeSkill__c employeeSkill2 = new EmployeeSkill__c(
            Name = 'Test2',
            Assigned_Time__c = 6,
            Employee__c = employee1.Id,
            Project__c = project1.Id
        );


        EmployeeSkill__c employeeSkill3 = new EmployeeSkill__c(
            Name = 'Test3',
            Assigned_Time__c = 7,
            Employee__c = employee1.Id,
            Project__c = project1.Id
        );
 
        Test.startTest();
        Database.SaveResult result = Database.insert(employeeSkill2, false);
        Database.SaveResult resultWithError = Database.insert(employeeSkill3, false);
        Test.stopTest();
 
        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
 
        System.assert(!resultWithError.isSuccess());
        System.assert(resultWithError.getErrors().size() > 0);
    }
    
    @isTest static void TestUpdate() {
        EmployeeSkill__c[] queryResult1 = [
            SELECT Assigned_Time__c
            FROM EmployeeSkill__c
            WHERE Name = 'Test1'
        ];

        EmployeeSkill__c[] queryResult2 = [
            SELECT Assigned_Time__c
            FROM EmployeeSkill__c
            WHERE Name = 'Test2'
        ];

        EmployeeSkill__c employeeSkillSuccess = queryResult1[0];
        employeeSkillSuccess.Assigned_Time__c = 7;

        EmployeeSkill__c employeeSkillError = queryResult2[0];
        employeeSkillError.Assigned_Time__c = 8;



        Test.startTest();
        Database.SaveResult result = Database.update(employeeSkillSuccess, false);
        Database.SaveResult resultWithError = Database.update(employeeSkillError, false);
        Test.stopTest();
 
        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
 
        System.assert(!resultWithError.isSuccess());
        System.assert(resultWithError.getErrors().size() > 0);
    }
    
}