objects/Words__c.object
<CustomObject>
    <description>Words Database</description>
    <fields>
        <fullName>English__c</fullName>
        <description>Word or expression on English</description>
        <inlineHelpText>Enter English word(expression) here plz.</inlineHelpText>
        <label>English</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Russian__c</fullName>
        <description>Words on Russian</description>
        <inlineHelpText>Enter all words on Russian here.</inlineHelpText>
        <label>Russian</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>From what subject is the word?</description>
        <inlineHelpText>Enter short subject.</inlineHelpText>
        <label>Subject</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transcription__c</fullName>
        <label>Transcription</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Words</label>
    <nameField>
        <displayFormat>WN-{0000}</displayFormat>
        <label>Word Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Words</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WordsController.cls
public with sharing class WordsController {
    @AuraEnabled
    /* Return all objs 'Words__c' where Subject__c == subject */
    public static List<Words__c> getWordsBySubject(String subject) {
        return [
            SELECT English__c, Russian__c, Transcription__c, Subject__c
            FROM Words__c
            WHERE Subject__c = :subject
        ];
    }
    

    @AuraEnabled
    /* Return Subject__c DISTINCT */
    public static String[] getAllSubjectDistinct() {
        Set<Words__c> allWords = new Set<Words__c>([SELECT Subject__c FROM Words__c]);

        Set<String> uniqueSubjects = new Set<String>();
        
        for (Words__c value : allWords) {
            uniqueSubjects.add(value.Subject__c);
        }
        
        return new List<String>(uniqueSubjects);
    }
    
}